#ifndef __SoyError_h__
#define __SoyError_h__

#include "Error.h"

class SoyError : public Error {
 public:
  enum Code {
    ALLOCATION_FAILED = 0,
    VARIABLE_INDEX_OUT_OF_RANGE = 1,
    VARIABLE_DOESNT_EXIST_IN_SOLUTION = 2,
    PARTICIPATING_VARIABLE_MISSING_ASSIGNMENT = 3,
    NON_EQUALITY_INPUT_EQUATION_DISCOVERED = 4,
    SIMULATOR_ERROR = 5,
    MISSING_PL_CONSTRAINT_STATE = 6,
    REQUESTED_CASE_SPLITS_FROM_FIXED_CONSTRAINT = 7,
    UNBOUNDED_VARIABLES_NOT_YET_SUPPORTED = 8,
    EQUATION_INVALID = 9,
    RESTORING_ENGINE_FROM_INVALID_STATE = 10,
    RESTORATION_FAILED_TO_RESTORE_PRECISION = 11,
    CANNOT_RESTORE_TABLEAU = 12,
    FAILURE_TO_ADD_NEW_EQUATION = 13,
    RESTORATION_FAILED_TO_REFACTORIZE_BASIS = 14,
    FILE_DOESNT_EXIST = 15,
    MERGED_INPUT_VARIABLE = 16,
    MERGED_OUTPUT_VARIABLE = 17,
    INVALID_WEIGHTED_SUM_INDEX = 18,
    UNSUCCESSFUL_QUEUE_PUSH = 19,
    REQUESTED_NONEXISTENT_CASE_SPLIT = 20,
    UNABLE_TO_INITIALIZATION_PHASE_PATTERN = 21,
    BOUNDS_NOT_UP_TO_DATE_IN_LP_SOLVER = 22,
    UNEXPECTED_RETURN_STATUS_FROM_GUROBI = 23,
    ELIMINATE_PHASE_AFTER_PREPROECESSING = 24,
    UNABLE_TO_PICK_SPLIT_PLCONSTRAINT = 25,
    CONFLICT_HAS_PHASES_OF_SAME_PLCONSTRAINT = 26,
    INFEASIBILITY_DURING_OPTIMIZATION = 27,

    // Error codes for Query Loader
    FILE_DOES_NOT_EXIST = 100,
    INVALID_EQUATION_TYPE = 101,
    UNSUPPORTED_PIECEWISE_LINEAR_CONSTRAINT = 102,

    FEATURE_NOT_YET_SUPPORTED = 900,

    DEBUGGING_ERROR = 999,
  };

  SoyError(SoyError::Code code) : Error("SoyError", (int)code) {}

  SoyError(SoyError::Code code, const char *userMessage)
      : Error("SoyError", (int)code, userMessage) {}
};

#endif  // __SoyError_h__
